{"code":141,"level":"error","message":"Invalid function: \"firstOne\"","stack":"Error: Invalid function: \"firstOne\"\n    at handler (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\Routers\\FunctionsRouter.js:120:13)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\PromiseRouter.js:72:20\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T13:58:41.211Z"}
{"code":141,"level":"error","message":"Invalid function: \"firstOne\"","stack":"Error: Invalid function: \"firstOne\"\n    at handler (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\Routers\\FunctionsRouter.js:120:13)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\PromiseRouter.js:72:20\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T13:58:45.102Z"}
{"code":141,"level":"error","message":"Invalid function: \"firstOne\"","stack":"Error: Invalid function: \"firstOne\"\n    at handler (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\Routers\\FunctionsRouter.js:120:13)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\PromiseRouter.js:72:20\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T14:00:10.577Z"}
{"code":141,"level":"error","message":"Invalid function: \"firstOne\"","stack":"Error: Invalid function: \"firstOne\"\n    at handler (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\Routers\\FunctionsRouter.js:120:13)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\PromiseRouter.js:72:20\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T14:00:33.852Z"}
{"code":141,"level":"error","message":"Invalid function: \"firstOne\"","stack":"Error: Invalid function: \"firstOne\"\n    at handler (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\Routers\\FunctionsRouter.js:120:13)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\PromiseRouter.js:72:20\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T14:01:28.157Z"}
{"code":141,"level":"error","message":"Invalid function: \"firstOne\"","stack":"Error: Invalid function: \"firstOne\"\n    at handler (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\Routers\\FunctionsRouter.js:120:13)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\PromiseRouter.js:72:20\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T14:01:32.546Z"}
{"className":"Project","error":{"code":141,"message":"Parse.Cloud.getLogger is not a function"},"level":"error","message":"beforeSave failed for Project for user undefined:\n  Input: {\"title\":\"New contract\",\"description\":\"Description\",\"category\":\"Games\",\"subcategory\":\"Board\",\"urlProject\":\"https://v1docs.moralis.io/moralis-dapp/database/security#whitelist-domains\",\"urlSocials\":\"https://v1docs.moralis.io/moralis-dapp/database/security#whitelist-domains\",\"youtube\":\"\",\"goal\":1500,\"descM\":\"Some description\",\"type\":\"Standard\",\"owner\":\"0xa0a39c5823A51184043655711C8157ef4826447a\",\"state\":0,\"chainId\":80001,\"bookmarks\":[\"0xa0a39c5823A51184043655711C8157ef4826447a\"],\"verified\":false}\n  Error: {\"message\":\"Parse.Cloud.getLogger is not a function\",\"code\":141}","timestamp":"2022-12-03T15:24:34.986Z","triggerType":"beforeSave"}
{"code":141,"level":"error","message":"Parse.Cloud.getLogger is not a function","stack":"TypeError: Parse.Cloud.getLogger is not a function\n    at trigger (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\src\\cloud\\main.ts:40:30)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\triggers.js:882:25\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T15:24:34.990Z"}
{"error":{"code":141,"message":"Cannot read properties of undefined (reading 'providers')"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {\"custom\":\"custom\"}\n  Error: {\"message\":\"Cannot read properties of undefined (reading 'providers')\",\"code\":141}","params":{"custom":"custom"},"timestamp":"2022-12-03T16:04:07.262Z"}
{"code":141,"level":"error","message":"Cannot read properties of undefined (reading 'providers')","stack":"TypeError: Cannot read properties of undefined (reading 'providers')\n    at theFunction (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\src\\cloud\\main.ts:35:33)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\Routers\\FunctionsRouter.js:179:18\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:04:07.267Z"}
{"error":{"code":141,"message":"Cannot read properties of undefined (reading 'providers')"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {\"custom\":\"custom\"}\n  Error: {\"message\":\"Cannot read properties of undefined (reading 'providers')\",\"code\":141}","params":{"custom":"custom"},"timestamp":"2022-12-03T16:05:16.274Z"}
{"code":141,"level":"error","message":"Cannot read properties of undefined (reading 'providers')","stack":"TypeError: Cannot read properties of undefined (reading 'providers')\n    at theFunction (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\src\\cloud\\main.ts:35:33)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\parse-server\\src\\Routers\\FunctionsRouter.js:179:18\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:05:16.279Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {\"custom\":\"custom\"}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"funds(uint256)\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{"custom":"custom"},"timestamp":"2022-12-03T16:11:14.784Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:11:14.788Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {\"custom\":\"custom\"}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"funds(uint256)\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{"custom":"custom"},"timestamp":"2022-12-03T16:12:47.504Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:12:47.507Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {\"custom\":\"custom\"}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"funds(uint256)\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{"custom":"custom"},"timestamp":"2022-12-03T16:13:46.286Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:13:46.288Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"getConnectedMicroFunds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {\"custom\":\"custom\"}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"getConnectedMicroFunds(uint256)\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{"custom":"custom"},"timestamp":"2022-12-03T16:15:56.010Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"getConnectedMicroFunds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"getConnectedMicroFunds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:15:56.013Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"getConnectedMicroFunds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {\"custom\":\"custom\"}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"getConnectedMicroFunds(uint256)\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{"custom":"custom"},"timestamp":"2022-12-03T16:16:04.198Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"getConnectedMicroFunds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"getConnectedMicroFunds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:16:04.201Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {\"custom\":\"custom\"}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"funds(uint256)\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{"custom":"custom"},"timestamp":"2022-12-03T16:26:09.371Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:26:09.374Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {\"custom\":\"custom\"}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"funds(uint256)\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{"custom":"custom"},"timestamp":"2022-12-03T16:29:04.571Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:29:04.575Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"funds(uint256)\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{},"timestamp":"2022-12-03T16:29:22.016Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:29:22.019Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"funds(uint256)\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{},"timestamp":"2022-12-03T16:29:23.337Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"funds(uint256)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:29:23.339Z"}
{"error":{"code":141,"message":"processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":53,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"transaction underpriced\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_sendRawTransaction\\\",\\\"params\\\":[\\\"0x02f8718189018459682f008508c3474dc88252089477d3533eebaa48e54b6c69ef66149a25494c34e285e8d4a5100080c001a0b448f237ed33eacb5b15fff11913351e267c37fdb15a5e8fbdc547183670b184a05e3f3bf4b0c499ff98d2c28de88a3410a18b37cff7572c801989d4533a7823ee\\\"],\\\"id\\\":53,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://rpc-mainnet.maticvigil.com\", code=SERVER_ERROR, version=web/5.7.1)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {}\n  Error: {\"message\":\"processing response error (body=\\\"{\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\",\\\\\\\"id\\\\\\\":53,\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":-32000,\\\\\\\"message\\\\\\\":\\\\\\\"transaction underpriced\\\\\\\"}}\\\", error={\\\"code\\\":-32000}, requestBody=\\\"{\\\\\\\"method\\\\\\\":\\\\\\\"eth_sendRawTransaction\\\\\\\",\\\\\\\"params\\\\\\\":[\\\\\\\"0x02f8718189018459682f008508c3474dc88252089477d3533eebaa48e54b6c69ef66149a25494c34e285e8d4a5100080c001a0b448f237ed33eacb5b15fff11913351e267c37fdb15a5e8fbdc547183670b184a05e3f3bf4b0c499ff98d2c28de88a3410a18b37cff7572c801989d4533a7823ee\\\\\\\"],\\\\\\\"id\\\\\\\":53,\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\"}\\\", requestMethod=\\\"POST\\\", url=\\\"https://rpc-mainnet.maticvigil.com\\\", code=SERVER_ERROR, version=web/5.7.1)\",\"code\":141}","params":{},"timestamp":"2022-12-03T16:33:13.170Z"}
{"code":141,"level":"error","message":"processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":53,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"transaction underpriced\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_sendRawTransaction\\\",\\\"params\\\":[\\\"0x02f8718189018459682f008508c3474dc88252089477d3533eebaa48e54b6c69ef66149a25494c34e285e8d4a5100080c001a0b448f237ed33eacb5b15fff11913351e267c37fdb15a5e8fbdc547183670b184a05e3f3bf4b0c499ff98d2c28de88a3410a18b37cff7572c801989d4533a7823ee\\\"],\\\"id\\\":53,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://rpc-mainnet.maticvigil.com\", code=SERVER_ERROR, version=web/5.7.1)","stack":"Error: processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":53,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"transaction underpriced\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_sendRawTransaction\\\",\\\"params\\\":[\\\"0x02f8718189018459682f008508c3474dc88252089477d3533eebaa48e54b6c69ef66149a25494c34e285e8d4a5100080c001a0b448f237ed33eacb5b15fff11913351e267c37fdb15a5e8fbdc547183670b184a05e3f3bf4b0c499ff98d2c28de88a3410a18b37cff7572c801989d4533a7823ee\\\"],\\\"id\\\":53,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://rpc-mainnet.maticvigil.com\", code=SERVER_ERROR, version=web/5.7.1)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\web\\src.ts\\index.ts:341:28\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\web\\lib\\index.js:33:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\web\\lib\\index.js:14:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\web\\lib\\index.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:33:13.174Z"}
{"error":{"code":141,"message":"processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":53,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"transaction underpriced\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_sendRawTransaction\\\",\\\"params\\\":[\\\"0x02f8718189018459682f0085051ff07b048252089477d3533eebaa48e54b6c69ef66149a25494c34e285e8d4a5100080c080a0ca07c768d882c55d899002b80b43a2e3bbaca0914fbe5b1d4107fb0c738ce16da01246691a5f6db3dbca593553129c852154cf7e4b0d002cc71f363d93abfd05f5\\\"],\\\"id\\\":53,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://rpc-mainnet.maticvigil.com\", code=SERVER_ERROR, version=web/5.7.1)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {}\n  Error: {\"message\":\"processing response error (body=\\\"{\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\",\\\\\\\"id\\\\\\\":53,\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":-32000,\\\\\\\"message\\\\\\\":\\\\\\\"transaction underpriced\\\\\\\"}}\\\", error={\\\"code\\\":-32000}, requestBody=\\\"{\\\\\\\"method\\\\\\\":\\\\\\\"eth_sendRawTransaction\\\\\\\",\\\\\\\"params\\\\\\\":[\\\\\\\"0x02f8718189018459682f0085051ff07b048252089477d3533eebaa48e54b6c69ef66149a25494c34e285e8d4a5100080c080a0ca07c768d882c55d899002b80b43a2e3bbaca0914fbe5b1d4107fb0c738ce16da01246691a5f6db3dbca593553129c852154cf7e4b0d002cc71f363d93abfd05f5\\\\\\\"],\\\\\\\"id\\\\\\\":53,\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\"}\\\", requestMethod=\\\"POST\\\", url=\\\"https://rpc-mainnet.maticvigil.com\\\", code=SERVER_ERROR, version=web/5.7.1)\",\"code\":141}","params":{},"timestamp":"2022-12-03T16:39:27.725Z"}
{"code":141,"level":"error","message":"processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":53,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"transaction underpriced\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_sendRawTransaction\\\",\\\"params\\\":[\\\"0x02f8718189018459682f0085051ff07b048252089477d3533eebaa48e54b6c69ef66149a25494c34e285e8d4a5100080c080a0ca07c768d882c55d899002b80b43a2e3bbaca0914fbe5b1d4107fb0c738ce16da01246691a5f6db3dbca593553129c852154cf7e4b0d002cc71f363d93abfd05f5\\\"],\\\"id\\\":53,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://rpc-mainnet.maticvigil.com\", code=SERVER_ERROR, version=web/5.7.1)","stack":"Error: processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":53,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"transaction underpriced\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_sendRawTransaction\\\",\\\"params\\\":[\\\"0x02f8718189018459682f0085051ff07b048252089477d3533eebaa48e54b6c69ef66149a25494c34e285e8d4a5100080c080a0ca07c768d882c55d899002b80b43a2e3bbaca0914fbe5b1d4107fb0c738ce16da01246691a5f6db3dbca593553129c852154cf7e4b0d002cc71f363d93abfd05f5\\\"],\\\"id\\\":53,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://rpc-mainnet.maticvigil.com\", code=SERVER_ERROR, version=web/5.7.1)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\web\\src.ts\\index.ts:341:28\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\web\\lib\\index.js:33:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\web\\lib\\index.js:14:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\web\\lib\\index.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:39:27.728Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"name()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"name()\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{},"timestamp":"2022-12-03T16:43:32.443Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"name()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"name()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:43:32.449Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"name()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"name()\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{},"timestamp":"2022-12-03T16:44:38.060Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"name()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"name()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:44:38.063Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"symbol()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"symbol()\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{},"timestamp":"2022-12-03T16:46:18.050Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"symbol()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"symbol()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:46:18.053Z"}
{"error":{"code":141,"message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"symbol()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"},"functionName":"firstOne","level":"error","message":"Failed running cloud function firstOne for user undefined with:\n  Input: {}\n  Error: {\"message\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"symbol()\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\",\"code\":141}","params":{},"timestamp":"2022-12-03T16:47:08.945Z"}
{"code":141,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"symbol()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"symbol()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:269:28)\n    at Logger.throwError (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\logger\\src.ts\\index.ts:281:20)\n    at Interface.decodeFunctionResult (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\abi\\src.ts\\interface.ts:427:23)\n    at Contract.<anonymous> (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\src.ts\\index.ts:400:44)\n    at step (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\Uzivatel\\dac\\crypto\\eye\\parse\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-03T16:47:08.949Z"}
